### ISSUE TITLE
Automounting archives

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-file-manager#30]
In the past it was possible to auto-mount archive files as it were media just by right clicking on them and opening them with the application "Archive Mounter".

It happens that it no longer works. As seen in the comment section of the [Arch Linux Automounter package](https://aur.archlinux.org/packages/automounter), its [desktop file](https://aur.archlinux.org/cgit/aur.git/tree/mount-archive.desktop?h=automounter) seems to be working on GNOME but not in Deepin.

The root cause seems to be the file manager not recognising properly the exec line, specifically the strings "%u" and "%f".

These don't work:
`Exec=/usr/lib/gvfsd-archive file=%u`
`Exec=/usr/lib/gvfsd-archive file=%f`

But this does:
`Exec=/usr/lib/gvfsd-archive file=[FILE]`

**Comment by BLumia** [comment]
Hi and thank you for the feedback!

It seems is a bug, but probable it's not a bug of dde-file-manager, hope you can provide some extra informations.

Please run the file manager app from terminal and select the "Archive Mounter" application from the "Open with" menu, then you'll got some log from `stdout`. At that time, can you see a log says `launchApp by gio: <your desktop file info>` ? And, you can also install d-feet and check if there is a interface called `com.deepin.StartManager` from `com.deepin.SessionManager` (a Session Bus).

Since the file manager have two different ways to do this action ([related source code if you are interested](https://github.com/linuxdeepin/dde-file-manager/blob/465c65c436d2a01cd4473915d5b09ae99ab79a8e/dde-file-manager-lib/shutil/fileutils.cpp#L529)) so we should find out which one have the issue you've mentioned. That will be quite helpful to help us find out where the bug is. Thank you very much!

**Comment by es20490446e** [comment]
- [Log](https://github.com/linuxdeepin/dde-file-manager/files/2228012/Log.txt)

**Comment by BLumia** [comment]
Thank you for the info. That's a bug of [startdde](https://github.com/linuxdeepin/startdde) and I've helped you reported the bug to related developer, please wait for more update :)

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/go-lib/+/37179/

**Comment by BLumia** [comment]
This should be fixed after the package maintainer update the related packages, feel free to reopen this issue if you got any further problem about this issue :)
