### ISSUE TITLE
Search query result did not view new file

### ISSUE THREAD

**Issue by rizmut** [linuxdeepin/dde-file-manager#37]
**Description**
A file manager should record **every** change happens in file system, including if there's new file exist. Deepin File Manager could not view new file while refreshing search query in same directory working. 

This bug is considerably critical..

**To Reproduce**

1. Go to a particular directory
2. Create a new file, e.g with 'test.txt' name
3. Click search button and fill "test" without double quotes
4. The file is not shown

**Expected behavior**
The new file is shown

**Enviroments:**
 - Distro: Linux Deepin 15.7
 - Kernel: `Linux laptop-bajau 4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018 x86_64 GNU/Linux`
 - Deepin File Manager version : 1.8.1

**Comment by BLumia** [comment]
Can't reproduce om my machine.. This should works under x86_64 with deepin-anything enabled.

Try `apt policy dde-file-manager` and `ps -e | grep deepin-anything`, then paste the output here, thx.

**Comment by rizmut** [comment]
`dde-file-manager:
  Installed: 4.6.6-3
  Candidate: 4.6.6-3
  Version table:
 *** 4.6.6-3 500
        500 http://kartolo.sby.datautama.net.id/deepin panda/main amd64 Packages
        100 /var/lib/dpkg/status
`

`5414 ?        00:00:00 deepin-anything`

**Comment by BLumia** [comment]
Ah, probably it's a bug of deepin-anything.

Please check if you did enabled the internal and external device indexing in the option menu, if it's enabled, disable it and see if that fix the problem.

Still not figure out what the problem is, but that can be a workaround for this issue. :joy: 

------------

The associated config file located at `~/.config/deepin/dde-file-manager.json`, under `GenericAttribute` section:

``` json
"GenericAttribute": {
        ...
        "IndexExternal": false,
        "IndexInternal": false,
        ...
},
```

**Comment by rizmut** [comment]
From the options window, apart from external storage, I find Auto index internal disk has been enabled by default. The bug happens in internal disk. So I would try to enable external disk also

This is my `~/.config/deepin/dde-file-manager.json`

```{
    "GenericAttribute": {
        "ShowedFileSuffixOnRename": true,
        "ShowedHiddenFiles": true
    }
}
```

**Comment by BLumia** [comment]
> The bug happens in internal disk. So I would try to enable external disk also

Try disable it (both the internal one and the external one) and see if it can solve this issue. It can be a workaround before we find out and fix the actual bug.

**Comment by rizmut** [comment]
After enabling both internal and external disk auto index, I've found this bug disappear in system directory (my home directory) but still happens in internal disk (/media/Data).

And after disabling both auto index, the bug disappear completely. So strange.

Oh, and I hope Deepin File Manager incorporate search as type just like Nautilus do. It seems DFM stuck in  XP's explorer/ nautilus 2.x search capability.

**Comment by BLumia** [comment]
I still don't know what caused the bug, still can't reproduce here :joy: . We'll fix it once we found the problem. Thank you for reporting this. btw we have plan about enhance the search function in the future update..

**Comment by rizmut** [comment]
One more requested feature is the capability to see recent item in the main window as well as in the open dialog.

**Comment by BLumia** [comment]
> One more requested feature is the capability to see recent item in the main window as well as in the open dialog.

Actually we also have plan about adding that feature...

In order to make things clearly, keep one issue for one specific bug / feature request. You can open up another issue for your newer feature request / bug report which is not related to this bug.

We do not yet got a proper issue guideline for now (in fact most of the dde repo only accept bug report from the [developer-center]()'s issue tracker), you can take a look at [this article from kde](https://community.kde.org/Get_Involved/Bug_Reporting#One_issue_per_bug_report) to know how to help developers out by submitting issues in a more effective way :)

**Comment by rizmut** [comment]
I actually know that my feature request should not posted here. But literally I'm very happy with your fast response so I do. Lol. One more off topic, could you please give me a link that contains a list of planning feature for all Deepin software?

**Comment by BLumia** [comment]
> One more off topic, could you please give me a link that contains a list of planning feature for all Deepin software?

We do not yet got a public-visible roadmap now, once it's ready. you can find it at [here](https://www.deepin.org/en/developer-community/planning/) :)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
