### ISSUE TITLE
Bug / Shortcoming ... while polling a folder to know its size ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-file-manager#39]
Hi,

Seems there is bug or a possible shortcoming that hadn't been factored into the design ...

turns out the behavior reported here ...
https://github.com/flatpak/flatpak/issues/2037

is an issue with the file manager mistaking hard links as actual items polling them for their size resulting in an inaccurate 'Folder Size'

**Comment by BLumia** [comment]
In linux, every folder got at least one hard link to the actual data, we have two ways to fix it: don't count file size if it's a hard link which linked to more than two files (i don't think this is a good approach), or just treat all hard link as-is. [Please read this first](https://en.wikipedia.org/wiki/Hard_link).

btw, please don't ignore the issue template.

**Comment by aiamuzz** [comment]
Oh ... you closed the issue !!!

Honestly what you say is a little too technical for me to understand it fully ... but i can say this much this issue isn't replicated in the Nautilus file manager ... i installed and tested it specifically for this issue ... 

am not clear of Your closing of this issue, is it bcos it can't be resolved or it doesn't really matter ???

**PS : as a non-technical user / tester ... taking the time out to report anomalies is as far we can go !!!**

**Comment by BLumia** [comment]
@aiamuzz 

> Honestly what you say is a little too technical for me to understand it fully ... but i can say this much this issue isn't replicated in the Nautilus file manager ... 

I means actually a normal folder is also a hard link, so if you created a hard link for a folder, then there are two folders(or say, two hard links) are pointed to the same data, in this case there are really no different between these two folders(hard links), so if we are going to check the file size, simply ignoring hard link with more than one file linked is not a good approach.

Personally I recommend you read the _hard link wikipedia page_ first so it will probably help you understand the reason.

> am not clear of Your closing of this issue, is it bcos it can't be resolved or it doesn't really matter ???

Yeah, it's designed to be like this. We are ignoring soft link, but not hard link, so it's actually not a bug and then I closed the issue, simple as that.

If you got any good idea about how we could deduplicate, feel free to update this issue and reopen it.

> taking the time out to report anomalies is as far we can go !!!

Sorry about make you feel bad but closing an issue don't means you did anything wrong, your issue is still helpful but if an issue is invalid (e.g. It's not a bug / It's designed to be like this), leave the issue open really can did nothing since we have still a lot of things to work on. Thank you for the feedback anyway :)

**Comment by janxkoci** [comment]
The `du` command as well as Nautilus give the right answer about the folder size - why you cannot do the same again?

**Comment by BLumia** [comment]
Actually I'm not sure about the reason of the old designed behavior and I've asked the product manager once about this issue, as the result we leave it as-is but I still don't know the reason :(

Anyway if anyone would like to working on this issue, feel free to leave a patch here, and I'd like to ask about changing the behavior, help review code and merge it :)
