### ISSUE TITLE
Mail links aren't working on Chromium under Deepin

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-file-manager#42]
In case you wanted to fix it yourselves, here's the [upstream bug](https://bugs.freedesktop.org/show_bug.cgi?id=107877).

**Comment by BLumia** [comment]
Thanks for reporting this, but are you trying to enter `mailto:example@domain.com` to the file manager's address bar? The file manager doesn't support `mailto:` by design.

If you are reporting a bug related to DDE, you should post your issue to the [Developer Center](https://github.com/linuxdeepin/developer-center) instead of this repo, since this repo it's only for the file manager app, thank you :)

**Comment by es20490446e** [comment]
Most likely this is better dealt with on [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=882273). Otherwise I will report to the [Developer Center](https://github.com/linuxdeepin/developer-center) as you said.

Thank you.

**Comment by es20490446e** [comment]
I fixed it [upstream](https://bugs.freedesktop.org/show_bug.cgi?id=107877#c3).
