### ISSUE TITLE
Cannot type spaces in folder names

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-file-manager#5]
- [How to reproduce](https://youtu.be/kxttFa9NniY)
- Deepin File Manager 1:4.4.8.3-1
- Manjaro Deepin Stable

**Comment by BLumia** [comment]
Thank you for reporting this issue :)

This issue has been fixed in [this commit](https://cr.deepin.io/#/c/dde/dde-file-manager/+/33919/) at branch [develop2.0](https://cr.deepin.io/#/admin/projects/dde/dde-file-manager,branches). (the sync bot seems stop working these days so the code is not yet synced to GitHub), you can clone the code and build it by yourself if you need this fix right now.

If you don't want to build it by yourself, you can temporary type the filename/foldername without space and then add the missing space character, and wait for the package maintainer delive the new version of the file manager.

Enjoy.😄

**Comment by es20490446e** [comment]
Thank you ;)
