### ISSUE TITLE
Freezing when clicking on a folder in Android.

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#53]
## Describe the bug
I cannot copy any file from Android to my computer.

*A clear and concise description of what the bug is.*
I have a Samsung J500H android. When I try to select a folder in android and if the selected folder has too many files or folders, then everything including the whole DE freezes.

## To Reproduce
To reproduce it, just try to select a folder in a Samsung Android phone. Note that the folder should have a lot of files in it.

## Expected behavior
Nothing should be freezing when trying to select a folder in Android.
*A clear and concise description of what you expected to happen.*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environments *(please complete the following information):*

 - Distro: Linux Deepin 15.]
 - Version: 1.8.2

**Comment by gitawego** [comment]
I have the same issue when exploring a local network folder, i think it's caused by trying to count folder items

**Comment by rubenvdham** [comment]
Does this happen using nautilus as well? I experience the same using nautilus and windows. It seems MTP and/or bandwidth is the issue.

**Comment by dimti** [comment]
Freezes also exists for me with remote ssh-folders.
Slowly freezes.
I think, on version of deepin-file-manager 4.8.6 is no problem. But in newest package versions problem with freezes is actual.

Problem exists in 5.0 and 4.8.8 version:
`# pacman -U deepin-file-manager-1:4.8.8.1-1-x86_64.pkg.tar.xz
загрузка пакетов...
предупреждение: откат версии пакета deepin-file-manager (1:5.0.0-1 => 1:4.8.8.1-1)`

Problem may be not in 4.8.6 version:
`# pacman -U deepin-file-manager-1:4.8.6.2-1-x86_64.pkg.tar.xz
загрузка пакетов...
предупреждение: откат версии пакета deepin-file-manager (1:4.8.8.1-1 => 1:4.8.6.2-1)`

I unable test on version 4.8.6, because i can\`t run deepin-file-manager 4.8.6 with newly other packages in my system:
https://pastebin.com/pXVPmBCc

Uhh. between 4.8.6 and 4.8.8 passed over many commits. And changed dozen of files
![image](https://user-images.githubusercontent.com/582144/64948218-431e0d80-d87f-11e9-95b9-934a207c9147.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
