### ISSUE TITLE
"Run as root" option

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#56]
When we have to run or open a program with root privileges in the file manager, we always have to open up a terminal and type a command or two. It is very annoying.

## Describe the solution you'd like

I think the best solution would be to add a "Run as root" option in the file manager.

**Comment by BLumia** [comment]
I don't think it's a good idea since we should always avoid using root privilege directly. If some application really need the root privilege, developer should use `pkexec` or something similar to acquire privilege. 

User should know what he/she is doing when they attempted to use root privilege, introduce a "Run as root" is just like telling user "whoops, seems it doesn't works, let's try run as root and see if it works" and that's really bad imo.

**Comment by BLumia** [comment]
After discussion with product manager, we are not going to implement this feature. Gotta close this issue.

If you really need this feature, you can write a simple content menu extension if you like.

Anyway, thanks for the idea :)
